version: '3.8'

services:
  ollama:
    build:
      context: .
      dockerfile: docker/ollama/Dockerfile
    container_name: ai-chat-ollama
    ports:
      - "12500:11434"
    volumes:
      - ./.ollama/models:/root/.ollama/models      
    environment:
      - OLLAMA_HOST=0.0.0.0
      - OLLAMA_PORT=11434
    networks:
      - ai-chat-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434/api/tags"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

  app:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    container_name: ai-chat-app
    ports:
      - "8000:8000"
      - "3000:3000"
    volumes:
      - ./.data:/app/data
    environment:
      - OLLAMA_HOST=ollama
      - OLLAMA_PORT=11434
      - OLLAMA_BASE_URL=http://ollama:11434
    depends_on:
      ollama:
        condition: service_healthy
    networks:
      - ai-chat-network
    restart: unless-stopped

volumes:
  ollama_data:
    driver: local

networks:
  ai-chat-network:
    driver: bridge
